repos:
  - repo: local
    hooks:
      - id: check-changelog
        name: check changelog
        entry: uv run scripts/check_changelog.py
        language: system
        pass_filenames: false
        files: (^|.+/)(CHANGELOG\.md|__version__\.py)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        name: ruff-fix
        args: [--fix, --select=RUF022, --select=I]
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.4
    hooks:
      - id: uv-lock
        files: (^|.+/)(uv\.lock|pyproject\.toml|uv\.toml)$
