# common Compose configuration for all environments
services:
  bot:
    depends_on:
      - postgres
    stop_signal: SIGINT
    secrets:
      - source: env  # created in overrides to fix relative path issues
        target: /app/.env
    environment:
      API_PORT: 5000
      API_ROOT_PATH: ''
      DB_URL: postgresql+psycopg://postgres:postgres@postgres/postgres
      HEALTH_CHECK_URL: http://localhost:5000/health

  postgres:
    image: postgres:17
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
