# common Compose configuration for all environments
services:
  bot:
    stop_signal: SIGINT
    volumes:
      - data:/app/data
    secrets:
      - source: env  # created in overrides to fix relative path issues
        target: /app/.env
    environment:
      API_PORT: 5000
      API_ROOT_PATH:
      HEALTH_CHECK_URL: http://localhost:5000/health

volumes:
  data:
